services:
  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs
    ports:
      - "9044:9000"
      - "9045:9001"
    environment:
      RUSTFS_ACCESS_KEY: radiouser
      RUSTFS_SECRET_KEY: radiopass123
    volumes:
      - rustfs_data:/data

  postgres:
    image: postgres:16-alpine
    container_name: radio-postgres
    environment:
      POSTGRES_USER: radio
      POSTGRES_PASSWORD: radiopass123
      POSTGRES_DB: radio
    ports:
      - "5455:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # radio:
  #   build: .
  #   container_name: radio-server
  #   depends_on:
  #     - rustfs
  #     - postgres
  #   env_file:
  #     - .env
  #   ports:
  #     - "8080:8080"

volumes:
  rustfs_data:
  postgres_data: