services:
  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs
    ports:
      - "9044:9000"
      - "9045:9001"
    environment:
      RUSTFS_ACCESS_KEY: radiouser
      RUSTFS_SECRET_KEY: radiopass123
    volumes:
      - rustfs_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"] 
      interval: 5s
      timeout: 5s
      retries: 5

  # postgres:
  #   image: postgres:16-alpine
  #   container_name: radio-postgres
  #   environment:
  #     POSTGRES_USER: radio
  #     POSTGRES_PASSWORD: radiopass123
  #     POSTGRES_DB: radio
  #   ports:
  #     - "5455:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  radio:
    build:
      context: ./backend
    container_name: radio-server
    depends_on:
      rustfs:
        condition: service_healthy
      # - postgres
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"

  web:
    build:
      context: ./frontend
      args:
        PUBLIC_RADIO_URL: "http://192.168.196.17:8080"
    container_name: radio-web
    depends_on:
      - radio
    environment:
      - RADIO_INTERNAL_URL=http://192.168.196.17:8080
      - ORIGIN=http://192.168.196.17:3000
      - BODY_SIZE_LIMIT=50M
    ports:
      - "3000:3000"

volumes:
  rustfs_data:
  postgres_data: